name: Tag

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  get_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.result }}
    steps:
      - uses: actions/checkout@v2
      - id: version
        run: cat VERSION

  release:
    needs: [get_version]
    runs-on: ubuntu-latest
    if: ${{ fromJSON(needs.get_version.outputs.version) }}
    steps:
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ needs.get_version.outputs.version }}
      - uses: softprops/action-gh-release@v1
        with:
          body: "Foo"
          name: v${{ needs.get_check.outputs.version }}
          tag_name: v${{ needs.get_check.outputs.version }}
          target_commitish: ${{ github.ref_name }}
