name: Tag

on:
  push:
    branches:
      - main

jobs:
  getter:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.out }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
      - run: python .ci/get_changelog.py
      - id: version
        run: echo "::set-output name=out::$(python .ci/get_version.py)"

  release:
    needs: [getter]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: softprops/action-gh-release@v1
        with:
          name: v${{ needs.getter.outputs.version }}
          tag_name: v${{ needs.getter.outputs.version }}
          target_commitish: ${{ github.ref_name }}
          generate_release_notes: true
